# Test config
in_path: "/app/data/encoded/redandblack.bin"
out_path: "/app/data/transcoded/redandblack_tc.bin"

num_video_coder_threads: 1

codec_params:
  video_occupancy:
    fps: 30
    preset: "fast"

  video_geometry:
    fps: 30
    preset: "fast"

  video_attribute:
    fps: 30
    preset: "fast"