occPreset: ultrafast
occEncThreads: 2
occEncodingMode: "AI" # AI or RA

geoPreset: ultrafast
geoEncThreads: 2
geoEncodingMode: "AI"
geoQP: 32

attPreset: ultrafast
attEncThreads: 2
attEncodingMode: "AI"
attQP: 42
