occPreset: ultrafast
occEncThreads: 2
occEncodingMode: "AI" # AI or RA

geoPreset: ultrafast
geoEncThreads: 3
geoEncodingMode: "AI"
geoQP: 32

attPreset: ultrafast
attEncThreads: 3
attEncodingMode: "AI"
attQP: 42
