occPreset: ultrafast
occEncThreads: 2
occEncodingMode: "AI" # AI or RA

geoPreset: ultrafast
geoEncThreads: 8
geoEncodingMode: "AI"
geoQP: 32

attPreset: ultrafast
attEncThreads: 8
attEncodingMode: "AI"
attQP: 42
